### ISSUE TITLE
Problems opening or saving STL files with replicatorg

### ISSUE THREAD

**Issue by djemili** [makerbot/ReplicatorG#201] opened 2011-02-01 21:00 UTC
Hello,

I have a problem opening STL files with replicatorg-0023. I didn't know if the if the problem was saving or opening because I actually can open dowloaded files. Once I do an action to the model, for instance rotate, and I save a new file, then I can not open the new file.

I have generated simple files with openSCAD and I have found the same problem.

I tried with both java interpreters: openjdk6 and jre (the Sun closed one).

And I have two computers, one with archlinux and the other with Ubuntu 10. I tried in both computers the same things (not everything but almost). I paste here the error output:

INFO: Loading /home/emili/Downloads/modhex1r.stl
01/02/2011 21:50:12 replicatorg.app.ui.modeling.PreviewPanel setScene
INFO: /home/emili/Downloads/modhex1r.stl
01/02/2011 21:50:12 org.j3d.loaders.stl.STLASCIIParser2 readObjectStats
INFO: Got name Default
01/02/2011 21:50:12 org.j3d.loaders.stl.STLASCIIParser2 readObjectStats
INFO: Parsed object name[Default] facets 497
01/02/2011 21:50:12 replicatorg.model.BuildModel loadShape
INFO: Could not load /home/emili/Downloads/modhex1r.stl with STLLoader
java.lang.NumberFormatException: For input string: "-5,125105e-17"
        at sun.misc.FloatingDecimal.readJavaFormatString(FloatingDecimal.java:1242)
        at java.lang.Double.parseDouble(Double.java:527)
        at org.j3d.loaders.stl.STLASCIIParser2.readVector(STLASCIIParser2.java:64)
        at org.j3d.loaders.stl.STLASCIIParser2.getNextFacet(STLASCIIParser2.java:75)
        at org.j3d.loaders.stl.STLFileReader.getNextFacet(STLFileReader.java:164)
        at org.j3d.renderer.java3d.loaders.STLLoader.createScene(STLLoader.java:171)
        at org.j3d.renderer.java3d.loaders.STLLoader.load(STLLoader.java:118)
        at org.j3d.renderer.java3d.loaders.STLLoader.load(STLLoader.java:86)
        at replicatorg.model.BuildModel.loadShape(BuildModel.java:68)
        at replicatorg.model.BuildModel.loadShape(BuildModel.java:98)
        at replicatorg.model.BuildModel.getShape(BuildModel.java:57)
        at replicatorg.app.ui.modeling.EditingModel.makeShape(EditingModel.java:85)
        at replicatorg.app.ui.modeling.EditingModel.getGroup(EditingModel.java:146)
        at replicatorg.app.ui.modeling.PreviewPanel.setScene(PreviewPanel.java:88)
        at replicatorg.app.ui.modeling.PreviewPanel.setModel(PreviewPanel.java:76)
        at replicatorg.app.ui.MainWindow.setModel(MainWindow.java:1412)
        at replicatorg.app.ui.MainWindow.handleOpen2(MainWindow.java:2107)
        at replicatorg.app.ui.MainWindow.checkModified2(MainWindow.java:1957)
        at replicatorg.app.ui.MainWindow.checkModified(MainWindow.java:1865)
        at replicatorg.app.ui.MainWindow$41.run(MainWindow.java:2073)
        at java.awt.event.InvocationEvent.dispatch(InvocationEvent.java:226)
        at java.awt.EventQueue.dispatchEvent(EventQueue.java:602)
        at java.awt.EventDispatchThread.pumpOneEventForFilters(EventDispatchThread.java:275)
        at java.awt.EventDispatchThread.pumpEventsForFilter(EventDispatchThread.java:200)
        at java.awt.EventDispatchThread.pumpEventsForHierarchy(EventDispatchThread.java:190)
        at java.awt.EventDispatchThread.pumpEvents(EventDispatchThread.java:185)
        at java.awt.EventDispatchThread.pumpEvents(EventDispatchThread.java:177)
        at java.awt.EventDispatchThread.run(EventDispatchThread.java:138)
01/02/2011 21:50:12 replicatorg.model.BuildModel loadShape
INFO: Could not load /home/emili/Downloads/modhex1r.stl with ObjLoader
java.lang.IllegalArgumentException: TriangleArray: illegal vertexCount
        at javax.media.j3d.TriangleArray.<init>(TriangleArray.java:67)
        at org.j3d.renderer.java3d.loaders.ObjLoader.load(ObjLoader.java:106)
        at org.j3d.renderer.java3d.loaders.ObjLoader.load(ObjLoader.java:36)
        at replicatorg.model.BuildModel.loadShape(BuildModel.java:68)
        at replicatorg.model.BuildModel.loadShape(BuildModel.java:104)
        at replicatorg.model.BuildModel.getShape(BuildModel.java:57)
        at replicatorg.app.ui.modeling.EditingModel.makeShape(EditingModel.java:85)
        at replicatorg.app.ui.modeling.EditingModel.getGroup(EditingModel.java:146)
        at replicatorg.app.ui.modeling.PreviewPanel.setScene(PreviewPanel.java:88)
        at replicatorg.app.ui.modeling.PreviewPanel.setModel(PreviewPanel.java:76)
        at replicatorg.app.ui.MainWindow.setModel(MainWindow.java:1412)
        at replicatorg.app.ui.MainWindow.handleOpen2(MainWindow.java:2107)
        at replicatorg.app.ui.MainWindow.checkModified2(MainWindow.java:1957)
        at replicatorg.app.ui.MainWindow.checkModified(MainWindow.java:1865)
        at replicatorg.app.ui.MainWindow$41.run(MainWindow.java:2073)
        at java.awt.event.InvocationEvent.dispatch(InvocationEvent.java:226)
        at java.awt.EventQueue.dispatchEvent(EventQueue.java:602)
        at java.awt.EventDispatchThread.pumpOneEventForFilters(EventDispatchThread.java:275)
        at java.awt.EventDispatchThread.pumpEventsForFilter(EventDispatchThread.java:200)
        at java.awt.EventDispatchThread.pumpEventsForHierarchy(EventDispatchThread.java:190)
        at java.awt.EventDispatchThread.pumpEvents(EventDispatchThread.java:185)
        at java.awt.EventDispatchThread.pumpEvents(EventDispatchThread.java:177)
        at java.awt.EventDispatchThread.run(EventDispatchThread.java:138)
[Fatal Error] :1:1: Content is not allowed in prolog.
01/02/2011 21:50:12 org.j3d.loaders.collada.ColladaParser parse
INFO: Could not configure parser
org.xml.sax.SAXParseException; lineNumber: 1; columnNumber: 1; Content is not allowed in prolog.
        at com.sun.org.apache.xerces.internal.parsers.DOMParser.parse(DOMParser.java:253)
        at com.sun.org.apache.xerces.internal.jaxp.DocumentBuilderImpl.parse(DocumentBuilderImpl.java:288)
        at org.j3d.loaders.collada.ColladaParser.parse(ColladaParser.java:183)
        at org.j3d.renderer.java3d.loaders.ColladaLoader.loadInternal(ColladaLoader.java:62)
        at org.j3d.renderer.java3d.loaders.ColladaLoader.load(ColladaLoader.java:32)
        at replicatorg.model.BuildModel.loadShape(BuildModel.java:68)
        at replicatorg.model.BuildModel.loadShape(BuildModel.java:104)
        at replicatorg.model.BuildModel.getShape(BuildModel.java:57)
        at replicatorg.app.ui.modeling.EditingModel.makeShape(EditingModel.java:85)
        at replicatorg.app.ui.modeling.EditingModel.getGroup(EditingModel.java:146)
        at replicatorg.app.ui.modeling.PreviewPanel.setScene(PreviewPanel.java:88)
        at replicatorg.app.ui.modeling.PreviewPanel.setModel(PreviewPanel.java:76)
        at replicatorg.app.ui.MainWindow.setModel(MainWindow.java:1412)
        at replicatorg.app.ui.MainWindow.handleOpen2(MainWindow.java:2107)
        at replicatorg.app.ui.MainWindow.checkModified2(MainWindow.java:1957)
        at replicatorg.app.ui.MainWindow.checkModified(MainWindow.java:1865)
        at replicatorg.app.ui.MainWindow$41.run(MainWindow.java:2073)
        at java.awt.event.InvocationEvent.dispatch(InvocationEvent.java:226)
        at java.awt.EventQueue.dispatchEvent(EventQueue.java:602)
        at java.awt.EventDispatchThread.pumpOneEventForFilters(EventDispatchThread.java:275)
        at java.awt.EventDispatchThread.pumpEventsForFilter(EventDispatchThread.java:200)
        at java.awt.EventDispatchThread.pumpEventsForHierarchy(EventDispatchThread.java:190)
        at java.awt.EventDispatchThread.pumpEvents(EventDispatchThread.java:185)
        at java.awt.EventDispatchThread.pumpEvents(EventDispatchThread.java:177)
        at java.awt.EventDispatchThread.run(EventDispatchThread.java:138)

Is it a bug? Or may be something in my configuration?

**Comment by PeterS242** [comment] 2011-02-04 19:22
It looks like this is an Openscad bug that has been fixed in the source but isn't in any binary release yet.

You can see the fix by browsing to the source code on github and search for "Applied comma radix bugfix by jmarsden" (June 26, 2010).

You can compile a new version from source or wait until the next release.

Peter

http://rocklinux.net/pipermail/openscad/2010-June/000453.html
https://github.com/openscad/openscad/commit/8af73de90a9b1d1be58bbd2956066a9182d3bdc4

**Comment by cibomahto** [comment] 2011-03-04 21:49
Hi, are you still having this issue, and can you provide a sample stl that triggers it? I'm not able to duplicate the error.

**Comment by PeterS242** [comment] 2011-03-04 22:04
It relies mainly on system locale settings.  If you change your system's locale to one that uses "," instead of "." with regards to decimal notation (Germany is one) then you will see the problem.

1)  Change system locale to Germany
2)  Run Openscad, open a SCAD file, and output as an STL
*)  Openscad will output the STL using the Decimal Place settings defined by the locale of the system ("," instead of "." in this case)
3)  Run ReplicatorG and attempt to open the STL
4)  Errors should be emitted

**Comment by PeterS242** [comment] 2011-03-04 22:32
I am not able to reproduce this under Windows XP.  I will try this with Ubuntu 10.

**Comment by cibomahto** [comment] 2011-03-04 22:53
Hey Peter, are you certain this is the same issue djemili is having (or are you the same person?) From the initial report, it sounded like the problem was with editing models (scale/rotate) in ReplicatorG, not openSCAD.

**Comment by djemili** [comment] 2011-03-08 09:33
Hi all,

I solved the OpenSCAD part of the problem by downloading the last version and compiling it myself as PeterS242 suggested. Thanks!. But I'm still having the problem with ReplicatorG: I can not open a file that I modified and saved myself.

I'm going to try changing locale options in Ubuntu.. but in the step 2 I use ReplicatorG.

I upload the STL file if still not working.

thanks.

**Comment by cibomahto** [comment] 2011-03-09 06:47
Cool, thanks for the update.

**Comment by phooky** [comment] 2011-09-13 15:37
Should be fixed by 30f52c1b2df6542197a6b193ca9d37e5ae126a6f.

**Closed as completed by phooky** 2011-09-13 15:37 UTC

**Comment by djemili** [comment] 2011-09-23 10:01
Yes. It is already fixed. Thanks for your help :)
